[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nbpy"
version = "0.1.0"
description = "A tool to process notebook cells and output to a file"
authors = [
    { name="Xu Jingwen", email="threadcup@gmail.com" }
]

[project.scripts]
nbpy = "nbpy:cli"